POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "weiwei@gmail.com",
  "password": "123"
}

###
POST http://localhost:8000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcklkIjoiN2JjMjM4M2QtMjA4NS00MWRkLWEwYjgtZjZjYzQyYTAyOTE3IiwibmFtZSI6IndlaSIsImVtYWlsIjoid2Vpd2VpQGdtYWlsLmNvbSJ9LCJpYXQiOjE2OTg1NjUxMjEsImV4cCI6MTcwMTE1NzEyMSwidHlwZSI6InJlZnJlc2gifQ.6jUwJehM-JjpLKoN3HRCIINXzdwqH2Cac2hdipJyi4s"
}

###
POST http://localhost:8000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcklkIjoiN2JjMjM4M2QtMjA4NS00MWRkLWEwYjgtZjZjYzQyYTAyOTE3IiwibmFtZSI6IndlaSIsImVtYWlsIjoid2Vpd2VpQGdtYWlsLmNvbSJ9LCJpYXQiOjE2OTg1NjU1NDIsImV4cCI6MTcwMTE1NzU0MiwidHlwZSI6InJlZnJlc2gifQ.g4ItfHnvtTL9UFni2AMRIiflKMwHR7o-SuH0xmCTXYg"
}

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "priema",
  "email": "priema@gmail.com",
  "password": "123"
}

###
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsibmFtZSI6IndlaSIsImVtYWlsIjoid2Vpd2VpQGdtYWlsLmNvbSIsInVzZXJJZCI6IjdiYzIzODNkLTIwODUtNDFkZC1hMGI4LWY2Y2M0MmEwMjkxNyJ9LCJpYXQiOjE2OTg1NjU1NjgsImV4cCI6MTY5ODU2NzM2OCwidHlwZSI6ImFjY2VzcyJ9.YgdUf__wz9lVQngviY_IvmI3p8x89Ij1vxR4k2mJ_5M