POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "weiwei@gmail.com",
  "password": "123"
}

###
POST http://localhost:8000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcklkIjoiN2JjMjM4M2QtMjA4NS00MWRkLWEwYjgtZjZjYzQyYTAyOTE3IiwibmFtZSI6IndlaSIsImVtYWlsIjoid2Vpd2VpQGdtYWlsLmNvbSJ9LCJpYXQiOjE2OTg1NjM2OTQsImV4cCI6MTcwMTE1NTY5NCwidHlwZSI6InJlZnJlc2gifQ.akv__Xrxob31PcPY_XJFHCKVkzOJRfmp3wPWulk7M9U"
}

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "priema",
  "email": "priema@gmail.com",
  "password": "123"
}

###
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcklkIjoiN2JjMjM4M2QtMjA4NS00MWRkLWEwYjgtZjZjYzQyYTAyOTE3IiwibmFtZSI6IndlaSIsImVtYWlsIjoid2Vpd2VpQGdtYWlsLmNvbSJ9LCJpYXQiOjE2OTg0MjgwNjQsImV4cCI6MTY5ODQyOTg2NCwidHlwZSI6ImFjY2VzcyJ9.3PZdRy0uSQA5ixkuEic_t4MOIdr_TXIrPztW6T99-Ww